//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctftcConverter.serviceCtctf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceCtctf.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stc", ReplyAction="*")]
        double stc(double ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stc", ReplyAction="*")]
        System.Threading.Tasks.Task<double> stcAsync(double ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stf", ReplyAction="*")]
        double stf(double tf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stf", ReplyAction="*")]
        System.Threading.Tasks.Task<double> stfAsync(double tf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ctftcConverter.serviceCtctf.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ctftcConverter.serviceCtctf.WebService1Soap>, ctftcConverter.serviceCtctf.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double stc(double ct) {
            return base.Channel.stc(ct);
        }
        
        public System.Threading.Tasks.Task<double> stcAsync(double ct) {
            return base.Channel.stcAsync(ct);
        }
        
        public double stf(double tf) {
            return base.Channel.stf(tf);
        }
        
        public System.Threading.Tasks.Task<double> stfAsync(double tf) {
            return base.Channel.stfAsync(tf);
        }
    }
}
